name: CI Pipeline (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version Tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest  # Changed from self-hosted to GitHub-hosted Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Updated to newer Temurin distribution (formerly AdoptOpenJDK)
          
      - name: Build with Maven
        run: mvn clean install
        
      - name: Configure Docker credentials
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}' # Updated to match your secret name
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCR_REGISTRY }} # Added registry parameter
        
      - name: Build and Push Docker image
        env:
          IMAGE_NAME: ${{ secrets.GCR_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/pk-app-1 # Updated app name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG