name: CI - Manual Build Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version Tag'
        required: true
        default: 'v1.0.0'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: pk-app-1
  IMAGE_TAG: ${{ github.event.inputs.version }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    
    steps:
      - name: Set Full Image Name
        run: |
          echo "FULL_IMAGE_NAME=${{ secrets.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
        shell: bash
      
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Verify Environment
        run: |
          echo "Checking Maven version..."
          mvn --version
          
          echo "Checking Docker version..."
          docker version
        
      - name: Build with Maven
        run: |
          echo "Building application with Maven..."
          mvn clean package -DskipTests
          
      - name: Build Docker Image
        run: |
          echo "Building Docker image: ${{ env.FULL_IMAGE_NAME }}"
          docker build -t ${{ env.FULL_IMAGE_NAME }} .
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GCR_REGISTRY }} --quiet
          
      - name: Push to Container Registry
        run: |
          echo "Pushing image to: ${{ env.FULL_IMAGE_NAME }}"
          docker push ${{ env.FULL_IMAGE_NAME }}
          
      - name: Clean Up
        if: always()
        run: |
          echo "Cleaning up resources..."
          docker rmi ${{ env.FULL_IMAGE_NAME }} || true

