name: CI Pipeline (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version Tag'
        required: true
        default: 'v-1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # STAGE 1: Setup & Checkout
      - name: Checkout code
        uses: actions/checkout@v2
      
      # STAGE 2: Security Scanning
      - name: GitLeaks Security Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          fail_build: true
          verbose: true
      
      # STAGE 3: Java Build Environment Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # STAGE 4: Maven Build    
      - name: Build with Maven
        run: |
          echo "===== STARTING MAVEN BUILD STAGE ====="
          mvn clean install
          echo "===== MAVEN BUILD COMPLETED ====="
      
      # STAGE 5: GCP Authentication    
      - name: Configure Google Cloud Authentication
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Verify Service Account
        run: |
          echo "===== VERIFYING GCP SERVICE ACCOUNT ====="
          gcloud auth list
          echo "===== GCP VERIFICATION COMPLETED ====="
      
      # STAGE 6: Docker Configuration    
      - name: Configure Docker for Artifact Registry
        run: |
          echo "===== CONFIGURING DOCKER FOR GCP ARTIFACT REGISTRY ====="
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          echo "===== DOCKER CONFIGURATION COMPLETED ====="
      
      # STAGE 7: Docker Build and Push    
      - name: Build and Push Docker image
        env:
          IMAGE_NAME: "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pk-docker-repo-dev/app-1"
          IMAGE_TAG: "${{ github.event.inputs.version }}"
        run: |
          echo "===== STARTING DOCKER BUILD STAGE ====="
          echo "Building image: ${IMAGE_NAME}:${IMAGE_TAG}"
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          echo "===== DOCKER BUILD COMPLETED ====="
          
          echo "===== STARTING DOCKER PUSH STAGE ====="
          echo "Pushing image: ${IMAGE_NAME}:${IMAGE_TAG}"
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          echo "===== DOCKER PUSH COMPLETED ====="
          
          echo "===== CI PIPELINE COMPLETED SUCCESSFULLY ====="