name: CI Pipeline (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version Tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest  # Changed from self-hosted to GitHub-hosted Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Updated to newer Temurin distribution (formerly AdoptOpenJDK)
          
      - name: Build with Maven
        run: mvn clean install
        
      - name: Configure Docker credentials
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: Configure Docker
        run: |
          # Print registry for debugging
          echo "Configuring Docker auth for Artifact Registry"
          # Configure Docker for Artifact Registry
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
      - name: Build and Push Docker image
        env:
          # Using Artifact Registry format: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE
          IMAGE_NAME: "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pk-app-1/app"
          IMAGE_TAG: ${{ github.event.inputs.version }}
        run: |
          echo "Building and pushing: ${IMAGE_NAME}:${IMAGE_TAG}"
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${IMAGE_NAME}:${IMAGE_TAG}