name: CI/CD with Dockerized Stages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version Tag'
        required: true
        default: 'v1.0.0'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: pk-app-1 # Changed to lowercase
  IMAGE_TAG: ${{ github.event.inputs.version }}

jobs:
  build-and-deploy:
    runs-on: self-hosted # Runner label for your self-hosted runner
    env:
      FULL_IMAGE: ${{ secrets.GCR_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Docker access
        run: |
          echo "Checking Docker version and permissions..."
          docker version
          docker info

      # 1. GitLeaks scan
      - name: Run GitLeaks inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            zricethezav/gitleaks:latest detect -s /repo

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2 # Changed from ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 2. Maven build
      - name: Run Maven Build inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v ${{ env.HOME }}/.m2:/root/.m2 \ # Mount cached Maven repository
            -w /app \
            maven:3.9.6-eclipse-temurin-17 \
            mvn clean install

      # 3. Docker build
      - name: Build Docker Image
        run: |
          docker build -t $FULL_IMAGE .

      # 4. Authenticate to GCP & Push to GCR
      - name: Verify gcloud CLI
        run: |
          echo "Checking gcloud CLI version..."
          gcloud --version

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ secrets.GCR_REGISTRY }}

      - name: Push Docker Image to GCR
        run: |
          docker push $FULL_IMAGE

